dist: trusty
sudo: false
language: cpp

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - g++-5

script:
   - mkdir build
   - cd build
   - cmake -D ENABLE_COVERAGE:BOOL=TRUE ..
   - make
   - ./unit_tests
   - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-5
